name: biometric_storage_darwin
description: iOS and macOS implementation of the biometric_storage federated plugin.
version: 5.1.1-dev.2
homepage: https://github.com/authpass/biometric_storage/
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  biometric_storage_platform_interface:
    path: ../biometric_storage_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=5.0.0 <7.0.0'

flutter:
  plugin:
    implements: biometric_storage
    platforms:
      ios:
        pluginClass: BiometricStoragePlugin
        dartPluginClass: BiometricStorageDarwin
      macos:
        pluginClass: BiometricStorageMacOSPlugin
        dartPluginClass: BiometricStorageDarwin
